<div class="space-y-4">
    <div class="grid gap-4 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-4">
        <div><label for="transfer-filter-search" class="mb-1 block text-sm font-medium">Search</label><input id="transfer-filter-search" type="search" wire:model.live.debounce.300ms="search" maxlength="255" placeholder="Number, SKU or remarks" class="w-full rounded-lg border border-slate-300 px-3 py-2"></div>
        <div><label for="transfer-filter-status" class="mb-1 block text-sm font-medium">Status</label><select id="transfer-filter-status" wire:model.live="status" class="w-full rounded-lg border border-slate-300 px-3 py-2"><option value="">All statuses</option>@foreach($statuses as $state)<option value="{{ $state->value }}">{{ strtoupper($state->value) }}</option>@endforeach</select></div>
        @foreach(['source' => 'Source warehouse', 'destination' => 'Destination warehouse'] as $field => $label)<div><label for="transfer-filter-{{ $field }}" class="mb-1 block text-sm font-medium">{{ $label }}</label><select id="transfer-filter-{{ $field }}" wire:model.live="{{ $field }}" class="w-full rounded-lg border border-slate-300 px-3 py-2"><option value="">All warehouses</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select></div>@endforeach
        <button type="button" wire:click="clearFilters" class="text-left text-sm underline">Clear filters</button>
    </div>
    <div class="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table class="w-full text-left text-sm"><thead class="bg-slate-50"><tr>@foreach(['Transfer', 'Source', 'Destination', 'Date', 'Status', 'Created by'] as $label)<th class="p-4">{{ $label }}</th>@endforeach</tr></thead><tbody>
        @forelse($transfers as $transfer)<tr wire:key="transfer-{{ $transfer->id }}" class="border-t"><td class="p-4"><a href="{{ route('stock-transfers.show', $transfer) }}" class="font-medium underline">{{ $transfer->number }}</a></td><td class="p-4">{{ $transfer->sourceWarehouse->code }}</td><td class="p-4">{{ $transfer->destinationWarehouse->code }}</td><td class="p-4">{{ $transfer->transfer_date?->format('Y-m-d') ?? '—' }}</td><td class="p-4">{{ strtoupper($transfer->status->value) }}</td><td class="p-4">{{ $transfer->creator->name }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">No stock transfers match your filters.</td></tr>@endforelse
    </tbody></table></div>
    {{ $transfers->links() }}<p wire:loading role="status">Loading transfers…</p>
</div>
